### ISSUE TITLE
REST API does not use `norm='l2'` by default for the feature extraction

### ISSUE THREAD

**Issue by rth** [FreeDiscovery/FreeDiscovery#111]
As reported by @eugene-yang , the REST API does not currently use `norm='l2'` by default for the feature extraction, while  it should. Besides,  for clustering, we are relying on the relationship between cosine and euclidean distances that assumes L2 normalized data. 

This would involve,
  - changing the `missing` parameter of `FeaturesParsSchema` in `freediscovery/server/schemas.py`
  - updating the docs in `FeaturesApi` class of `freediscovery/server/resources.py`

@eugene-yang a Pull request to fix this would be welcome. If you do, please make it from a different branch than `master` of your fork.  Also the REST API documentation for the `binary` parameter incorrectly says that it defaults to `True` while it's actually `False`.

**Comment by eugene-yang** [comment]
just did. Thank you.
