### ISSUE TITLE
Improve tests coverage

### ISSUE THREAD

**Issue by rth** [FreeDiscovery/FreeDiscovery#124]
The current code coverage for tests is [![codecov](https://codecov.io/gh/FreeDiscovery/FreeDiscovery/branch/master/graph/badge.svg)](https://codecov.io/gh/FreeDiscovery/FreeDiscovery) it would be useful to increase this number by adding tests to the sections of code that are not fully covered (cf. the link above for more information)...

**Comment by dmytrobondarchuk** [comment]
Hi, I'll try to add tests to the sections of code that are not fully covered.

**Comment by rth** [comment]
Thanks! That not so simple because most of sections that could be easily covered are often covered. The large uncovered sections in download dataset, categorization interpreration etc might require either using [mock](http://doc.pytest.org/en/latest/monkeypatch.html) or [pytest monkeypatching](http://doc.pytest.org/en/latest/monkeypatch.html)...

**Comment by rth** [comment]
Most parts of the code are covered. It's more of a continuous effort. Closing this.
