### ISSUE TITLE
Error on reload features after Feature Vectorizer

### ISSUE THREAD

**Issue by eugene-yang** [FreeDiscovery/FreeDiscovery#146]
I'm now using v1.1.0 and running text.FeatureVectorizer.
After calling FeatureVectorizer.ingest method, "features" file would appear in the feature directory. It seems like this file is dumped by joblib and I tried to load it through joblib again. This gives me a KeyError.

Here is the error message
```
KeyError                                  Traceback (most recent call last)
<ipython-input-2-ce07d02c961a> in <module>()
----> 1 joblib.load( "features" )

/Users/xxx/anaconda/lib/python3.6/site-packages/joblib/numpy_pickle.py in load(filename, mmap_mode)
    576                     return load_compatibility(fobj)
    577 
--> 578                 obj = _unpickle(fobj, filename, mmap_mode)
    579 
    580     return obj

/Users/xxx/anaconda/lib/python3.6/site-packages/joblib/numpy_pickle.py in _unpickle(fobj, filename, mmap_mode)
    506     obj = None
    507     try:
--> 508         obj = unpickler.load()
    509         if unpickler.compat_mode:
    510             warnings.warn("The file '%s' has been generated with a "

/Users/xxx/anaconda/lib/python3.6/pickle.py in load(self)
   1048                     raise EOFError
   1049                 assert isinstance(key, bytes_types)
-> 1050                 dispatch[key[0]](self)
   1051         except _Stop as stopinst:
   1052             return stopinst.value

KeyError: 29

```

**Comment by rth** [comment]
Thanks for reporting this.

This might be a backward compatibility issue in `joblib`: FreeDiscovery uses joblib in `sklearn.externals.joblib` (version 0.10.3) while the latest joblib version on PyPi is 0.11.0.

 Could you please see if changing the joblib import fixes it. 
Alternatively, `X = FeatureVectorizer(...)._load_features()` should also work..

**Comment by rth** [comment]
Closing this as fixed,. Please reopen if you still experience this issue...
