### ISSUE TITLE
Missing! build_tools/requirements_pip_unix.txt and _win.txt

### ISSUE THREAD

**Issue by kanecm** [FreeDiscovery/FreeDiscovery#52]
Install Instructions 2.a Python Install:

...
pip install -r build_tools/requirements_pip_unix.txt
pip install -r build_tools/requirements_pip_win.txt

both txt files missing from build_tools directory.

Used _comp.txt worked but who knows?

**Comment by kanecm** [comment]
Looks like the Instructions have been updated.

**Comment by rth** [comment]
@kanecm Yes, those corresponded to the previous version of the instructions that were updated since.
